sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t apurvsap/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true apurvsap/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env-2"
  bucket_name: "elasticbeanstalk-ap-south-1-202734100534"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

